config/routes.rb
Rails.application.routes.draw do
  resources :todos
    root 'todos#index'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:title, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Design</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true , 'bootstrap-sprockets' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <div id="main-container" class="container">
      <div class="row" >
        <div class="col-xs-3">
          <h3>Tealeaf Academy Todo</h3>
        </div>
        <div class="col-xs-9">
          <%= yield %>
        </div>
      </div>
    </div>
</body>
</html>

app/views/todos/_form.html.erb
<%= form_for(@todo,html: {class: "form-horizontal"}) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group ">
    <%= f.label :title ,class: "col-sm-2 control-label text-info"%>
    <div class="col-sm-10">
    <%= f.text_field :title,class: "form-control ", :placeholder=>"Title"  %>
  </div>
  </div>
  
  <div class="form-group">
   <%= f.label :notes ,class: "col-sm-2 control-label text-info" %>
    <div class="col-sm-10">
   <%= f.text_area :notes, class: "form-control", :placeholder=>"Write your notes here..." %>
  </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: "btn btn-success btn-lg" %>
   </div>
  </div>
 </form>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to @todo , class: 'btn btn-success active' do %>
<i class="glyphicon glyphicon-plus"></i> Show
<% end %> |
<%= link_to todos_path , class: 'btn btn-success active' do  %>
<i class="glyphicon glyphicon-plus"></i> Back
<% end %>

app/views/todos/index.html.erb
<h1>Listing todos</h1>

<table class='table table-striped table-hover table-condensed table-bordered'>
  <thead>
    <tr class='danger'>
      <th>Title</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr class='warning'>
        <td><%= todo.title %></td>
        <td><%= todo.notes %></td>
        <td><%= link_to 'Show', todo , class: 'btn btn-primary ' %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo), class: 'btn btn-info' %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure want to delete?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_todo_path, class: 'btn btn-success active' do %>
  <i class="glyphicon glyphicon-plus"></i> New Todo
<% end %>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to todos_path  class: 'btn btn-primary active' do %>
  <i class="glyphicon glyphicon-plus"></i> Back
  <% end %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p class="text-primary">>
  <strong><h2>Title:</h2></strong>
 <h2>  <%= @todo.title %></h2> 
</p>

<p class="text-info"> >
  <strong><h2>Notes:</h2></strong>
<h2>  <%= @todo.notes %> </h2>
</p>

<p class="text-muted">
<%= link_to edit_todo_path(@todo), class: 'btn btn-success active' do%> 
<i class="glyphicon glyphicon-plus"></i> Edit
<% end %>
<%= link_to todos_path, class: 'btn btn-success active' do %>
<i class="glyphicon glyphicon-plus"></i> Back
<% end %>
  
</p>